services:
- docker
sudo: required

install: 
# install google cloud sdk and kubernetes
- sudo apt-get clean && sudo apt-get update && sudo apt-get install -y apt-transport-https dpkg
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get update && sudo apt-get install google-cloud-sdk kubectl

before_script:
- cp .env-production server/.env
- cp .env-production client/.env
- docker-compose build service-template walking-suggestion-service anti-sedentary-service nginx > /dev/null
- docker-compose build server
- docker-compose build client > /dev/null

script:
- docker-compose run server python manage.py test
- docker-compose run client npm test
- docker-compose run client npm run build:app --prod

after_success:
# authenticate with gcloud and set up kubernetes
- gcloud auth activate-service-account --key-file=credentials/gce.json
- gcloud auth configure-docker -q
- gcloud config set project ${GAE_PROJECT_ID}
- gcloud container clusters get-credentials heartsteps-kpw --region=us-west1-a
# move app files into server
- gsutil -m rsync -dr client/www gs://heartsteps-assets/app
# generate website and upload
- docker-compose run -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER client npm run build:website --prod
- gsutil -m rsync -dr client/www gs://heartsteps-assets/website
# collect static files for server
- docker-compose run server python manage.py collectstatic
- gsutil -m rsync -dr server/static gs://heartsteps-assets/static
# upload images
- docker tag heartsteps_nginx gcr.io/heartsteps-kpwhri/heartsteps-nginx
- docker push gcr.io/heartsteps-kpwhri/heartsteps-nginx
- docker tag heartsteps_server gcr.io/heartsteps-kpwhri/heartsteps-server
- docker push gcr.io/heartsteps-kpwhri/heartsteps-server
- docker tag heartsteps_walking-suggestion-service gcr.io/heartsteps-kpwhri/walking-suggestion-service
- docker push gcr.io/heartsteps-kpwhri/walking-suggestion-service
- docker tag heartsteps_anti-sedentary-service gcr.io/heartsteps-kpwhri/anti-sedentary-service
- docker push gcr.io/heartsteps-kpwhri/anti-sedentary-service
# update kubernetes images...
- sed -i "s/DEFAULT_BUILD_NUMBER/'$TRAVIS_BUILD_NUMBER'/g" deployment.yaml
- kubectl apply -f deployment.yaml
# Migrate database
- docker-compose run server-gcloud python manage.py migrate
