services:
- docker
sudo: required

install: 
# install google cloud sdk
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk

script:
- cp .env-server .env
- source .env
- docker-compose run server python manage.py test
- docker-compose run client npm build test

after_success:
# login with gcloud
- gcloud auth activate-service-account --key-file=gce.json
- gcloud auth configure-docker -q
- gcloud config set project ${GAE_PROJECT_ID}
# migrate database
- docker-compose run server python manage.py migrate
# upload server static files to gae
- docker-compose run server python manage.py collectstatic
# move client files into server
- cp client/www server/app
# build the server image
- docker-compose build server
# upload client web app to gae
- docker tag heartsteps_server us.gcr.io/${GAE_PROJECT_ID}/heartsteps_server:v1
- docker push us.gcr.io/${GAE_PROJECT_ID}/heartsteps_server:v1
- gcloud app deploy app.yaml --image-url=us.gcr.io/${GAE_PROJECT_ID}/heartsteps_server:v1 -q
# upload ionic app to ionic pro