services:
- docker
sudo: required

install: 
# install google cloud sdk
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk

script:
- docker-compose run server python manage.py test
# Build client (for now)
- docker-compose run client npm install
- docker-compose run client ionic build --prod

after_success:
# move client files into server
- cp -r client/www server/app
# collect static files for server
- docker-compose run server python manage.py collectstatic
# migrate database
- docker run heartsteps_server ./migrate.sh
# login with gcloud
- gcloud auth activate-service-account --key-file=gce.json
- gcloud auth configure-docker -q
- gcloud config set project ${GAE_PROJECT_ID}
# upload client web app to gae
- gcloud app deploy server/app.yaml
# upload ionic app to ionic pro