services:
- docker
sudo: required

install: 
- docker-compose build service-template
# install google cloud sdk
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk

before_script:
- docker-compose build service-template walking-suggestion-service anti-sedentary-service > /dev/null
- docker-compose build server > /dev/null
- docker-compose build client > /dev/null

script:
- docker-compose run server python manage.py test
- docker-compose run client npm test
- docker-compose run client ionic build --prod

after_success:
- cp .env-production server/.env
- cp .env-production client/.env
# move client files into server
- cp -r client/www static/app
# collect static files for server
- docker-compose run server python manage.py collectstatic
- cp -r server/static static
# Migrate database
- docker-compose -f docker-compose.yaml -f docker-compose.gcloud.yaml run server python manage.py migrate
# login with gcloud
- gcloud auth activate-service-account --key-file=credentials/gce.json
- gcloud auth configure-docker -q
- gcloud config set project ${GAE_PROJECT_ID}
# upload images
- docker tag heartsteps_server gcr.io/heartsteps-kpwhri/heartsteps-server
- docker push gcr.io/heartsteps-kpwhri/heartsteps-server
- docker tag heartsteps_walking-suggestion-service gcr.io/heartsteps-kpwhri/walking-suggestion-service
- docker push gcr.io/heartsteps-kpwhri/walking-suggestion-service
- docker tag heartsteps_walking-suggestion-service gcr.io/heartsteps-kpwhri/walking-suggestion-service
- docker push gcr.io/heartsteps-kpwhri/walking-suggestion-service
# update kubernetes images...
