services:
- docker
sudo: required

install: 
# install google cloud sdk
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk

script:
- cp .env-server server/.env
- docker-compose build server
- docker-compose build client

after_success:
# migrate database
- docker-compose run server python3 manage.py migrate
# upload server static files to gae
- docker-compose run server python3 manage.py collectstatic
- gsutil cp -r server/static gs://heartsteps-static
# upload client web app to gae
# deploy new server images to gae
- docker tag heartsteps_server us.gcr.io/${GAE_PROJECT_ID}/heartsteps_server:v1
- docker push us.gcr.io/${GAE_PROJECT_ID}/heartsteps_server:v1 -q
- gcloud app deploy server/app.yaml --image-url=us.gcr.io/${GAE_PROJECT_ID}/heartsteps_server:v1 -q
# upload ionic app to ionic pro