apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: heartsteps-server
        image: gcr.io/heartsteps-kpwhri/heartsteps-server:latest
        imagePullPolicy: Always
        command: ['rabbitmq-server', 'start']
        ports:
        - containerPort: 5672

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heartsteps-server
  labels:
    app: heartsteps-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heartsteps-server
    spec:
      containers:
      - name: heartsteps-app
        image: gcr.io/heartsteps-kpwhri/heartsteps-server:latest
        imagePullPolicy: Always
        command: ['honcho', 'start', 'web', 'cloudsql']
        env:
          - name: ALLOWED_HOSTS
            value: '35.247.62.68'
          - name: SECRET_KEY
            value: 'ka6p=i&71njyh)hw%amk)p1)(a=u$#gpck-8!%^^51f^7g7b8o'
          - name: DATABASE_URL
            value: 'psql://heartsteps:heartsteps@/heartsteps?host=/cloudsql/heartsteps-kpwhri:us-west2:heartsteps-dev'
        ports:
        - containerPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heartsteps-worker
  labels:
    app: heartsteps-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heartsteps-worker
    spec:
      containers:
      - name: heartsteps-worker
        image: gcr.io/heartsteps-kpwhri/heartsteps-server:latest
        imagePullPolicy: Always
        command: ['honcho', 'start', 'celery', 'cloudsql']
        env:
          - name: ALLOWED_HOSTS
            value: '35.247.62.68'
          - name: SECRET_KEY
            value: 'ka6p=i&71njyh)hw%amk)p1)(a=u$#gpck-8!%^^51f^7g7b8o'
          - name: DATABASE_URL
            value: 'psql://heartsteps:heartsteps@/heartsteps?host=/cloudsql/heartsteps-kpwhri:us-west2:heartsteps-dev'
        ports:
        - containerPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: walking-suggestion-service
  labels:
    app: walking-suggestion-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: walking-suggestion-service
    spec:
      containers:
      - name: walking-suggestion-service
        image: gcr.io/heartsteps-kpwhri/walking-suggestion-service:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: anti-sedentary-service
  labels:
    app: anti-sedentary-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anti-sedentary-service
    spec:
      containers:
      - name: anti-sedentary-service
        image: gcr.io/heartsteps-kpwhri/anti-sedentary-service:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: heartsteps-server
  labels:
    app: heartsteps-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: heartsteps-server

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  ports:
  - name: default
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    run: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: walking-suggestion
  labels:
    run: walking-suggestion
spec:
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    run: walking-suggestion-service
