version: '2'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  walking-suggestion:
    build: ./walking-suggestion
    command: python app.py
    volumes:
      - ./walking-suggestion:/walking-suggestion
    ports:
      - "5000:8080"
  anti-sedentary:
    build: ./anti-sedentary
    command: python app.py
    volumes:
      - ./anti-sedentary:/anti-sedentary
    ports:
      - "5001:8000"
  server:
    build: ./server
    env_file:
      - .env-development 
    command: honcho start web_dev celery rabbitmq
    volumes:
      - ./server:/server
      - ./credentials:/credentials
    ports:
      - "8080:8080"
    depends_on:
      - db
      - walking-suggestion
  client:
    build: ./client
    env_file:
      - .env-development
    command: ionic serve
    volumes:
      - ./client:/client
      - client-node-modules:/client/node_modules
      - ./credentials:/credentials
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    depends_on:
      - db
      - server
volumes:
  client-node-modules:
  pgdata:
