version: '2'

services:
  db:
    image: postgres
  server:
    build: ./server
    env_file: ./server/.env
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build: ./client
    command: ionic serve
    volumes:
      - ./client:/client
    ports:
      - "8100:8100"
    depends_on:
      - db
      - server