version: '2'

services:
  db:
    image: postgres
  server:
    build: ./server
    environment:
      - DEBUG=True
      - HOST_NAME=localhost
      - SECRET_KEY=secret_key
      - DATABASE_URL=psql://postgres@db:5432/postgres
      - FCM_SERVER_KEY=AAAA4ZxgfMQ:APA91bHz1XoVQPQrR19dVkn6cxl1A6ULe9tYLLFUH7G0mUzxxlrml2r5GZCsgn3MCduIKIKtV7-Di8egsm2lwjqD9aWPVDfyt8omWRYFr6RprULdrva9fSyaoe1LrI9nZ7Bokay38_7NZW-YY5_KcyBSr5j5pVEmdA
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build: ./client
    command: ionic serve
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "8100:8100"
      - "35729:35729" # live reload
      - "53703:53703" # Dev-app
    depends_on:
      - db
      - server