version: '2'

services:
  db:
    image: postgres
  server:
    build: ./server
    environment:
      - DEBUG=True
      - HOST_NAME=localhost,server
      - SECRET_KEY=secret_key
      - DATABASE_URL=psql://postgres@db:5432/postgres
      - FCM_SERVER_KEY=AAAA4ZxgfMQ:APA91bHz1XoVQPQrR19dVkn6cxl1A6ULe9tYLLFUH7G0mUzxxlrml2r5GZCsgn3MCduIKIKtV7-Di8egsm2lwjqD9aWPVDfyt8omWRYFr6RprULdrva9fSyaoe1LrI9nZ7Bokay38_7NZW-YY5_KcyBSr5j5pVEmdA
      - FITAPP_CONSUMER_KEY='22CXYZ'
      - FITAPP_CONSUMER_SECRET='3dccdbe583e49949b77d3f91a32064ef'
      - FITAPP_SUBSCRIBE=True
      - FITAPP_SUBSCRIBER_ID=1
      - FITAPP_VERIFICATION_CODE='271b6767cb997d86917a041b1693e2289510676613fe01df0306cbb24ef19d67'

    command: honcho start web_dev celery rabbitmq
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build: ./client
    command: ionic serve
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    depends_on:
      - db
      - server
  activity-suggestion:
    build: ./activity-suggestion
    command: python app.py
    volumes:
      - ./activity-suggestion:/activity-suggestion
    ports:
      - "5000:8000"
  anti-sedentary:
    build: ./anti-sedentary
    command: python app.py
    volumes:
      - ./anti-sedentary:/anti-sedentary
    ports:
      - "5001:8000"
