version: '2'

services:
  db:
    image: postgres
  server:
    build: ./server
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build: ./client
    env_file: .env
    command: ionic serve
    volumes:
      - ./client:/client
    ports:
      - "8100:8100"
      - "35729:35729" # live reload
      - "53703:53703" # Dev-app
    depends_on:
      - db
      - server