version: '2'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: ./server
    environment:
      - DEBUG=True
      - HOST_NAME=localhost,server
      - SECRET_KEY=secret_key
      - DATABASE_URL=psql://postgres@db:5432/postgres
      - FCM_SERVER_KEY=AAAAC9Cu-5M:APA91bEzy1tI3Ml_ROJGmABfdC5PJvpcCA2LqH4aRaHqBw4EDcViLkaTpgnDu1pY6kb79gSDcl_oTFAMLC4FgMiKgIx7GI0P4FgqDWfXYXW6sdq9B05WRmY91FXRsIriKNNa6x2IFWYC
      - FITAPP_CONSUMER_KEY=22CY6Y
      - FITAPP_CONSUMER_SECRET=8946c18e05b01acc82dd9947e39583c9
      - FITAPP_SUBSCRIBE=True
      - FITAPP_SUBSCRIBER_ID=1
      - FITAPP_VERIFICATION_CODE=41cc924fedb3f59d8f6f044bf28967f05a74c6e980ad0d985f1562864952ea33
    command: honcho start web_dev celery rabbitmq
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build: ./client
    command: ionic serve
    volumes:
      - ./client:/client
      - client-node-modules:/client/node_modules
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    depends_on:
      - db
      - server
  activity-suggestion:
    build: ./activity-suggestion
    command: python app.py
    volumes:
      - ./activity-suggestion:/activity-suggestion
    ports:
      - "5000:8000"
  anti-sedentary:
    build: ./anti-sedentary
    command: python app.py
    volumes:
      - ./anti-sedentary:/anti-sedentary
    ports:
      - "5001:8000"
volumes:
  client-node-modules:
  pgdata:
