version: '2'

services:
  db:
    image: postgres
  server:
    build: ./server/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: ./client/
    volumes:
      - ./client:/code
    ports:
      - "8100:8100"
    depends_on:
      - db
      - server