version: '2'
services:  
    anti-sedentary-service:
        build: ./anti-sedentary-service
        command: python app.py
        volumes:
            - ./anti-sedentary-service:/anti-sedentary-service
            - ./credentials:/credentials
        privileged: true
        ports:
            - "5001:8000"
    pooling-service:
        build: ./pooling-service
        command: python app.py
        volumes:
            - ./pooling-service:/pooling-service
            - ./credentials:/credentials
        ports:
            - "8888:8893"
            - "5002:8000"
    walking-suggestion-service:
        build: ./walking-suggestion-service
        command: python app.py
        volumes:
            - ./walking-suggestion-service:/walking-suggestion-service
            - ./credentials:/credentials
        ports:
            - "5000:8080"
        privileged: true
